#!/usr/bin/python3

def raise_exception_msg(message=""):
    try:
        print(1 / b)
    except NameError:
        return print('{}'.format(message))
